
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mbpgfkvtinmkubzrdcji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1icGdma3Z0aW5ta3VienJkY2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTc4MjUsImV4cCI6MjA2MDg5MzgyNX0.9RAh9PW-DqSaPO1DSn-EhR3a_tP2fXB6V0GTzld5wmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
